In [28]:
#EXERCICE 1
import numpy as np
X=np.array([[1,2,3],[4,5,6]])
A=X.tolist()
print(A)
#checking
print(type(A))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


In [1]:
#EXERCICE 2
n=np.random.randn(5,5)
print(n)
L=np.diag(n)
print(L)
somme=0
for i in L:
    somme=somme+i
print(somme)

[[-0.15791406  1.9428652   1.14575163  0.08075055  0.3962514 ]
 [ 1.48025694  0.49615092  1.417605   -1.061095    1.36992927]
 [ 0.5482076   2.7187702  -0.68867075 -0.91004172 -1.81856772]
 [-0.80412153 -0.43579044 -0.85157822 -0.05832448 -0.06506123]
 [ 1.29022722  1.01645819 -1.36059673 -0.67006485 -0.53185005]]
[-0.15791406  0.49615092 -0.68867075 -0.05832448 -0.53185005]
-0.9406084183638838


In [18]:
import numpy as np
C=np.array([[3,4,3,1,2,5,6,5,43,2,1],[2,4,3,1,2,6,4,2,7,9,0]])
x=int(input('Entrez le num'))
print(C[C>x])

Entrez le num3
[ 4  5  6  5 43  4  6  4  7  9]


In [22]:
A=np.array([[1,2,3],[1,4,5]])
B=np.array([[4,1,33],[13,4,4]])
C=np.add(A,B)
print(C)


[[ 5  3 36]
 [14  8  9]]
